[package]
name = "steiner"
version = "0.1.0"
authors = ["Matei Adriel <rafaeladriel11@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "5.1.1"
im = "15.0.0"
peg = "0.6.2"
common_macros = "0.1.1"